version: "3"
services:
  db:
    container_name: postgres-dev
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/iotdata
    ports:
      - "5432:5432"

volumes:
  pgdata: